version: '2'

services:

    elasticsearch:
        build:
            context: ./es
            dockerfile: Dockerfile
        ports:
            - 9200:9200
        # volumes:
        #     - ./es/init.d:/var/tmp/init.d
        environment:
            - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        ulimits:
            nofile:
                soft: 65536
                hard: 65536

    kibana:
        build:
            context: ./kibana
            dockerfile: Dockerfile
        ports:
            - 5601:5601
        volumes:
            - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
        depends_on:
            - elasticsearch

